# Page settings

baseURL = "https://michaelfischer.work/"
languageCode = "en"
title = "Michael Fischer"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#ff4757"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Michael Fischer"
        tagline = "Senior Software Engineer"
        avatar = "michi4.png"







    [params.contact]
        enable = true
        location = "Vienna, Austria"

        [[params.contact.list]]
        icon = "fas fa-mobile"
        url = "tel:#"
        text = "+43 680 3120111"
        [[params.contact.list]]
        icon = "fas fa-paper-plane"
        url = "mailto:#"
        text = "info@michaelfischer.work"
        [[params.contact.list]]
        icon = "fas fa-globe-europe"
        url = "#"
        text = "michaelfischer.work"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Languages"
        [[params.skills.list.items]]
        details = "• Java (7, 8, 11, 12)"
        [[params.skills.list.items]]
        details = "• HTML, XML, JSON, YAML, CSS/Sass, Markdown, XSLT"
        [[params.skills.list.items]]
        details = "• SQL (PostgreSQL, Oracle)"
        [[params.skills.list.items]]
        details = "• TypeScript, JavaScript, Groovy"


        [[params.skills.list]]
        title = "Frameworks & Technologies"
        [[params.skills.list.items]]
        details = "• Java EE, Spring, Spring Boot"
        [[params.skills.list.items]]
        details = "• Spring Security, Spring Roo, Spring Webflow"
        [[params.skills.list.items]]
        details = "• SOAP, Rest"
        [[params.skills.list.items]]
        details = "• JPA, Hibernate, Spring Data, MyBatis"
        [[params.skills.list.items]]
        details = "• Angular, GWT, Vaadin, JSF, JSP, Wicket"
        [[params.skills.list.items]]
        details = "• Maven, Gradle"
        [[params.skills.list.items]]
        details = "• JUnit, Spock, Mockito, EasyMock"
        [[params.skills.list.items]]
        details = "• Tomcat, IBM Websphere"
        [[params.skills.list.items]]
        details = "• Docker, Openshift"
        [[params.skills.list.items]]
        details = "• Micrometer, Grafana, Prometheus, InfluxDB"

        [[params.skills.list]]
        title = "Software"
        [[params.skills.list.items]]
        details = "• IntelliJ IDEA, Eclipse IDE, IBM Rational Application Developer"
        [[params.skills.list.items]]
        details = "• GIT, SVN, Rational Team Concert (Jazz)"
        [[params.skills.list.items]]
        details = "• Jenkins"
        [[params.skills.list.items]]
        details = "• JIRA, Confluence, Trello"
        [[params.skills.list.items]]
        details = "• MS Office, MS Project, Adobe Photoshop"

        [[params.skills.list]]
        title = "Other"
        [[params.skills.list.items]]
        details = "• Server Administration, DevOps, Firewalls"
        [[params.skills.list.items]]
        details = "• Thread Safety, Memory Optimization"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BSc in Media Informatics"
        university = "Vienna University of Technology"
        dates = "2006 - 2010"

        [[params.education.list]]
        degree = "Computer Science"
        university = "Reykjavik University"
        dates = "2008 - 2009"





    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "German"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "Spanish"
        level = "Beginner"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Music / Guitar"
        [[params.interests.list]]
        name = "Video Games"
        [[params.interests.list]]
        name = "Travelling"
        [[params.interests.list]]
        name = "Cooking"








    [params.summary]
        enable = true
        text = "I'm a java expert with a 10 year track record of building reliable and robust applications. It's important for me to build software which is not just 'running', but is extensible and maintainable. I was working on a variety of projects in the industries telecommunications, public services, education and otherse."



    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Sr. Software Engineer / Application Lead"
        dates = "2017 - current"
        company = "UCS - unique computing solutions, Vienna"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
#        [[params.experience.list.items]]
#        details = "Development of new Software components like payment systems, e-sim administration, phone number porting and many more"
#        [[params.experience.list.items]]
#        details = "Software Security"

        [[params.experience.list]]
        title = "Sr. Software Engineer / Lead Dev"
        dates = "2015 - 2016"
        company = "connex.cc, Vienna"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
#        [[params.experience.list.items]]
#        details = "Agile software development using SCRUM"
#        [[params.experience.list.items]]
#        details = "Responsible for architectural decisions regarding existing and new software projects"
#        [[params.experience.list.items]]
#        details = "Design and implementation of development processes and environments"
#        [[params.experience.list.items]]
#        details = "Coaching of colleagues"
#        [[params.experience.list.items]]
#        details = "Release, build and deployment management"

        [[params.experience.list]]
        title = "Software Engineer / IT Consultant"
        dates = "2016 - 2019"
        company = "Accenture Technology Solutions GmbH"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
#        [[params.experience.list.items]]
#        details = "Lorem ipsum dolor sit amet, consectetuer."
#        [[params.experience.list.items]]
#        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Programmer / QA Engineer"
        dates = "2009"
        company = "Tricentis Technology & Consulting GmbH, Vienna"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."






    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Online payment system for major austrian telco provider"
        meta = "2018-2019, with UCS"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
        additional = "Java, GWT, Spring Security, REST/CXF, Wirecard API"

        [[params.projects.list]]
        title = "Implementing eSIM Management for major austrian telco provider"
        meta = "2017, with UCS"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."
        additional = "Java, GWT, Spring Security, REST/CXF, Wirecard API"

        [[params.projects.list]]
        title = "Cryptocurrency Trading and Simulation Platform"
        meta = "2018-2019, Private"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."
        additional = "Java, GWT, Spring Security, REST/CXF, Wirecard API"

        [[params.projects.list]]
        title = "Private Cloud on baremetal server"
        meta = "2019, Private"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."
        additional = "Linux, Docker, bash, IPMI, "

        [[params.projects.list]]
        title = "Administrative platform for public educational organization"
        meta = "2015-2016, with connex.cc"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."
        additional = "Java, Vaadin, Spring Security, JPA, Spring Data, Spring REST, PostgreSQL"

        [[params.projects.list]]
        title = "Extension of scholarship administration system for a german ministry"
        meta = "2014 with Accenture"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."
        additional = "Java, Spring, IBM Websphere, JSF, Spring Webflow, Oracle"

        [[params.projects.list]]
        title = "Reimplementation of the tax and customs systems for an austrian ministry"
        meta = "2011-2014, with Accenture"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."
        additional = "Java, Spring, IBM Websphere, JSF, Spring Webflow, Oracle"










    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

       [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/brintal"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/michael-fischer-b242a7193/"





