# Page settings

baseURL = "https://michaelfischer.work/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#3399ff"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Michael Fischer"
        tagline = "Senior Software Engineer"
        avatar = "0.jpg"







    [params.contact]
        enable = true
        location = "Vienna, Austria"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+43 680 3120111"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "info@michaelfischer.work"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "michaelfischer.work"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Languages"
        [[params.skills.list.items]]
        details = "Java (7, 8, 11, 12)"
        [[params.skills.list.items]]
        details = "HTML"
        [[params.skills.list.items]]
        details = "CSS/Sass"
        [[params.skills.list.items]]
        details = "SQL (PostG"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Frameworks & Technologies"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BSc in Media Informatics"
        university = "Vienna University of Technology"
        dates = "2006 - 2010"

        [[params.education.list]]
        degree = "Computer Science"
        university = "Reykjavik University"
        dates = "2008 - 2009"





    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "German"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "Spanish"
        level = "Beginner"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Music"
        [[params.interests.list]]
        name = "Video Games"
        [[params.interests.list]]
        name = "Travelling"
        [[params.interests.list]]
        name = "Cooking"








    [params.summary]
        enable = true
        text = "I'm a Java-Expert with 10 years of relevant working experience and a broad knowlegde of both new and well-established technologies and frameworks. During my professional career I could gather valueable knowledge in various industries like telecommunications, education or public services and my international exposure further helps me to quickly adjust to different working environments and to communicate effectively. Through my deep understanding of the whole Java Ecosystem and my high standards in regards of application design, I constantly strive to deliver software components meeting the highest quality standards. Robust, well-designed software and clean, thourougly tested code are not just ideals for me but a minimum requirement."



    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Sr. Software Engineer / Application Lead"
        dates = "2017 - current"
        company = "UCS - unique computing solutions, Vienna"
        details = "Implementation and Maintenance of complex Application in the telecommunications industry"
        [[params.experience.list.items]]
        details = "Development of new Software components like payment systems, e-sim administration, phone number porting and many more"
        [[params.experience.list.items]]
        details = "Software Security"

        [[params.experience.list]]
        title = "Sr. Software Engineer / Lead Dev"
        dates = "2015 - 2016"
        company = "connex.cc, Vienna"
        details = "Design and implementation of dynamic web applications using various java technologies like Vaadin, Hibernate, Maven, Eclipse"
        [[params.experience.list.items]]
        details = "Agile software development using SCRUM"
        [[params.experience.list.items]]
        details = "Responsible for architectural decisions regarding existing and new software projects"
        [[params.experience.list.items]]
        details = "Design and implementation of development processes and environments"
        [[params.experience.list.items]]
        details = "Coaching of colleagues"
        [[params.experience.list.items]]
        details = "Release, build and deployment management"

        [[params.experience.list]]
        title = "Software Engineer / IT Consultant"
        dates = "2016 - 2019"
        company = "Accenture Technology Solutions GmbH"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Programmer / QA Engineer"
        dates = "2009 - 2009"
        company = "Tricentis Technology & Consulting GmbH, Vienna"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."






    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

       [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/brintal"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/michael-fischer-b242a7193/"





